### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by willemdh** [dfinke/OneGetGitHubProvider#1]
Hello,

I'm getting this error when trying to find all packages on my GitHub account. It seems to find some projects and then stops. Any idea what I'm doing wrong?

Grtz

PS C:\Windows\System32\WindowsPowerShell\v1.0> Find-Package -Source willemdh

Name                          Version      Status       ProviderName     Source           Summary

---

gistfile1.txt                 1.0          Available    Gist             willemdh         Blagist
check_lin_shellshock          1.0          Available    GitHub           willemdh
check_ms_cluster_preferred... 1.0          Available    GitHub           willemdh
check_ms_exchange_2010_health 1.0          Available    GitHub           willemdh
check_ms_kms                  1.0          Available    GitHub           willemdh
Find-Package : You cannot call a method on a null-valued expression.
At line:1 char:1
- Find-Package -Source willemdh
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : InvalidOperation: (Microsoft.Power...ets.FindPackage:FindPackage) [Find-Package], Except
    ion
  - FullyQualifiedErrorId : InvokeMethodOnNull,Microsoft.PowerShell.OneGet.CmdLets.FindPackage

**Comment by dfinke** [comment]
Thanks reporting that. I get the same error on my box. I'll take a look.

**Comment by dfinke** [comment]
Fixed summary property when GitHub has a null description

**Comment by willemdh** [comment]
How would I best update the module?

**Comment by dfinke** [comment]
You want to refresh it from GitHub? You want to use Update-Package. That feature is coming in the core OneGet component.
